
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

// Usando as chaves Supabase configuradas como segredos
const SUPABASE_URL = "https://mjofjyhxwywjzyqnnjsz.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1qb2ZqeWh4d3l3anp5cW5uanN6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ4MTU4NjgsImV4cCI6MjA2MDM5MTg2OH0.7-cC2YscScdGNb6VhTwtRi7cEMXTsoWGAwCLtrzesBI";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});
